
kind: pipeline
name: default

steps:
- name: test
  image: golang
  commands:
  - go test
  - go build

- name: publish
  image: plugins/docker
  settings:
    repo: registry.gitlab.com/iwaltgen/container-ci-test
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    # registry:
    #   from_secret: DOCKER_REGISTRY
    tags: [ latest, 1.0.0, 1 ]

---
