
kind: pipeline
name: default

steps:
- name: test
  image: golang
  commands:
  - go test
  - go build

- name: publish
  image: plugins/docker
  settings:
    repo: iwaltgen/isolated-ci-test
    tags: [ latest, 1.0.0, 1 ]
