image: docker:dind

stages:
  - build image

build server:
  stage: build image
  environment: development
  only:
    - master
  script:
    - docker info
    - echo "$REGISTRY_PASSWORD" | docker login -u $REGISTRY_USERNAME --password-stdin $REGISTRY_URL
    - docker build -t "$REGISTRY_URL/$CI_PROJECT_PATH" .
    - docker push "$REGISTRY_URL/$CI_PROJECT_PATH"
    - docker image rm "$REGISTRY_URL/$CI_PROJECT_PATH"
