image: docker:stable

services:
- docker:dind

variables:
  # DOCKER_HOST: tcp://docker:2375
  # DOCKER_DRIVER: overlay2
  DOCKER_IMAGE_NAME: $REGISTRY_URL/$CI_PROJECT_PATH

build server:
  stage: build
  only:
  - master
  script:
  - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD $REGISTRY_URL
  - docker build --pull -t $DOCKER_IMAGE_NAME .
  - docker push $DOCKER_IMAGE_NAME

# test e2e server:
#   stage: test
#   only:
#   - master
#   script:
#   - e2e-test.sh

# deploy server:
#   stage: deploy
#   environment:
#     name: development
#     url: dev.gitlab-ci-test.com
#   only:
#   - master
#   script:
#   - deploy.sh