image: docker:stable

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: $REGISTRY_URL/$CI_PROJECT_PATH

build server:
  stage: build
  environment:
    name: development
  # only:
  #   - master
  script:
    - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD $REGISTRY_URL
    - docker build --pull -t $IMAGE_NAME --cache-from $IMAGE_NAME .
    - docker push $IMAGE_NAME
