image: docker:stable

services:
  - docker:dind

stages:
  - build image

before_script:
  - echo "$REGISTRY_PASSWORD" | docker login -u $REGISTRY_USERNAME --password-stdin $REGISTRY_URL

build server:
  stage: build image
  environment: development
  only:
    - master
  script:
    - docker build -t "$REGISTRY_URL/$CI_PROJECT_PATH" .
    - docker push "$REGISTRY_URL/$CI_PROJECT_PATH"
    - docker image rm "$REGISTRY_URL/$CI_PROJECT_PATH"
