image: docker:latest

services:
  - docker:dind

stages:
  - build
  - push

before_script:
  - docker login -u $CI_USERNAME -p $CI_ACCESS_TOKEN $CI_REGISTRY

build-server:
  stage: build
  environment:
    name: master
  only:
  - master
  script:
    - echo 'build docker server image'
    - docker build -t "$CI_REGISTRY/$CI_PROJECT_PATH" .

push-docker-image:
  stage: push
  environment:
    name: master
  only:
  - master
  script:
    - echo 'push docker server image'
    - docker push "$CI_REGISTRY/$CI_PROJECT_PATH"
