
apiVersion: v1
kind: Service
metadata:
  name: container-ci-test
  namespace: sample
  labels:
    app: container-ci-test
spec:
  type: NodePort
  ports:
  - name: http
    nodePort: 30500
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: container-ci-test
